FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch

# Use the balenaCloud device variable
ARG EXPOSE_PORT
ENV EXPOSE_PORT ${EXPOSE_PORT}

# Install motion
RUN apt-get update && apt-get install -y motion 

# Add your customized config file
COPY motion.conf /etc/default/motion

# Copy the start script 
WORKDIR /motion
COPY start.sh ./

# Expose the port to access the webcam stream
EXPOSE $EXPOSE_PORT

# Start the streaming service
CMD [ "/bin/bash", "start.sh" ] 
